"project_id": "380544"
"api_token": "_secret_"
"base_url": "https://api.crowdin.com"
"preserve_hierarchy": true

"files":
  [
    {
      "source": "/intl/_us/*.json",
      "dest": "/_core_name_/%original_file_name%",
      "translation": "/intl/_%two_letters_code%/%original_file_name%",
    },
  ]
