CATEGORY_GB_LINK_LABEL "Game Boy Link"
CATEGORY_GB_LINK_INFO_0 "Configure networked 'Game Boy Link' (multiplayer) options."
GAMBATTE_GB_COLORIZATION_LABEL "GB Colorization"
GAMBATTE_GB_COLORIZATION_INFO_0 "Enables colorization of Game Boy games. 'Auto' selects the 'best' (most colorful/appropriate) palette. 'GBC' selects game-specific Game Boy Color palette if defined, otherwise 'GBC - Dark Green'. 'SGB' selects game-specific Super Game Boy palette if defined, otherwise 'SGB - 1A', 'Internal' uses 'Internal Palette' core option. 'Custom' loads user-created palette from system directory."
OPTION_VAL_AUTO "Auto"
OPTION_VAL_GBC "GBC"
OPTION_VAL_SGB "SGB"
OPTION_VAL_INTERNAL "Internal"
OPTION_VAL_CUSTOM "Custom"
GAMBATTE_GB_INTERNAL_PALETTE_LABEL "Internal Palette"
GAMBATTE_GB_INTERNAL_PALETTE_INFO_0 "Selects palette used for colorizing Game Boy games when 'GB Colorization' is set to 'Internal', or when 'GB Colorization' is set to 'Auto' and game has no pre-defined SGB/GBC palette. 'GB' palettes mimic the display of original Game Boy hardware. 'GBC' palettes are identical to the built-in presets of the Game Boy Color. 'SGB' palettes are identical to the built-in presets of the Super Game Boy."
OPTION_VAL_GB_DMG "GB - DMG"
OPTION_VAL_GB_POCKET "GB - Pocket"
OPTION_VAL_GB_LIGHT "GB - Light"
OPTION_VAL_GBC_BLUE "GBC - Blue"
OPTION_VAL_GBC_BROWN "GBC - Brown"
OPTION_VAL_GBC_DARK_BLUE "GBC - Dark Blue"
OPTION_VAL_GBC_DARK_BROWN "GBC - Dark Brown"
OPTION_VAL_GBC_DARK_GREEN "GBC - Dark Green"
OPTION_VAL_GBC_GRAYSCALE "GBC - Grayscale"
OPTION_VAL_GBC_GREEN "GBC - Green"
OPTION_VAL_GBC_INVERTED "GBC - Inverted"
OPTION_VAL_GBC_ORANGE "GBC - Orange"
OPTION_VAL_GBC_PASTEL_MIX "GBC - Pastel Mix"
OPTION_VAL_GBC_RED "GBC - Red"
OPTION_VAL_GBC_YELLOW "GBC - Yellow"
OPTION_VAL_SGB_1A "SGB - 1A"
OPTION_VAL_SGB_1B "SGB - 1B"
OPTION_VAL_SGB_1C "SGB - 1C"
OPTION_VAL_SGB_1D "SGB - 1D"
OPTION_VAL_SGB_1E "SGB - 1E"
OPTION_VAL_SGB_1F "SGB - 1F"
OPTION_VAL_SGB_1G "SGB - 1G"
OPTION_VAL_SGB_1H "SGB - 1H"
OPTION_VAL_SGB_2A "SGB - 2A"
OPTION_VAL_SGB_2B "SGB - 2B"
OPTION_VAL_SGB_2C "SGB - 2C"
OPTION_VAL_SGB_2D "SGB - 2D"
OPTION_VAL_SGB_2E "SGB - 2E"
OPTION_VAL_SGB_2F "SGB - 2F"
OPTION_VAL_SGB_2G "SGB - 2G"
OPTION_VAL_SGB_2H "SGB - 2H"
OPTION_VAL_SGB_3A "SGB - 3A"
OPTION_VAL_SGB_3B "SGB - 3B"
OPTION_VAL_SGB_3C "SGB - 3C"
OPTION_VAL_SGB_3D "SGB - 3D"
OPTION_VAL_SGB_3E "SGB - 3E"
OPTION_VAL_SGB_3F "SGB - 3F"
OPTION_VAL_SGB_3G "SGB - 3G"
OPTION_VAL_SGB_3H "SGB - 3H"
OPTION_VAL_SGB_4A "SGB - 4A"
OPTION_VAL_SGB_4B "SGB - 4B"
OPTION_VAL_SGB_4C "SGB - 4C"
OPTION_VAL_SGB_4D "SGB - 4D"
OPTION_VAL_SGB_4E "SGB - 4E"
OPTION_VAL_SGB_4F "SGB - 4F"
OPTION_VAL_SGB_4G "SGB - 4G"
OPTION_VAL_SGB_4H "SGB - 4H"
OPTION_VAL_SPECIAL_1 "Special 1"
OPTION_VAL_SPECIAL_2 "Special 2"
OPTION_VAL_SPECIAL_3 "Special 3"
OPTION_VAL_SPECIAL_4_TI_83_LEGACY "Special 4 (TI-83 Legacy)"
OPTION_VAL_TWB64_PACK_1 "TWB64 - Pack 1"
OPTION_VAL_TWB64_PACK_2 "TWB64 - Pack 2"
GAMBATTE_GB_PALETTE_TWB64_1_LABEL "> TWB64 - Pack 1 Palette"
GAMBATTE_GB_PALETTE_TWB64_1_INFO_0 "Selects internal colorization palette when 'Internal Palette' is set to 'TWB64 - Pack 1'."
OPTION_VAL_TWB64_001_AQOURS_BLUE "TWB64 001 - Aqours Blue"
OPTION_VAL_TWB64_002_ANIME_EXPO_VER "TWB64 002 - Anime Expo Ver."
OPTION_VAL_TWB64_003_SPONGEBOB_YELLOW "TWB64 003 - SpongeBob Yellow"
OPTION_VAL_TWB64_004_PATRICK_STAR_PINK "TWB64 004 - Patrick Star Pink"
OPTION_VAL_TWB64_005_NEON_RED "TWB64 005 - Neon Red"
OPTION_VAL_TWB64_006_NEON_BLUE "TWB64 006 - Neon Blue"
OPTION_VAL_TWB64_007_NEON_YELLOW "TWB64 007 - Neon Yellow"
OPTION_VAL_TWB64_008_NEON_GREEN "TWB64 008 - Neon Green"
OPTION_VAL_TWB64_009_NEON_PINK "TWB64 009 - Neon Pink"
OPTION_VAL_TWB64_010_MARIO_RED "TWB64 010 - Mario Red"
OPTION_VAL_TWB64_011_NICK_ORANGE "TWB64 011 - Nick Orange"
OPTION_VAL_TWB64_012_VIRTUAL_BOY_VER "TWB64 012 - Virtual Boy Ver."
OPTION_VAL_TWB64_013_GOLDEN_WILD "TWB64 013 - Golden Wild"
OPTION_VAL_TWB64_014_BUILDER_YELLOW "TWB64 014 - Builder Yellow"
OPTION_VAL_TWB64_015_CLASSIC_BLURPLE "TWB64 015 - Classic Blurple"
OPTION_VAL_TWB64_016_765_PRODUCTION_VER "TWB64 016 - 765 Production Ver."
OPTION_VAL_TWB64_017_SUPERBALL_IVORY "TWB64 017 - Superball Ivory"
OPTION_VAL_TWB64_018_CRUNCHYROLL_ORANGE "TWB64 018 - Crunchyroll Orange"
OPTION_VAL_TWB64_019_MUSE_PINK "TWB64 019 - Muse Pink"
OPTION_VAL_TWB64_020_NIJIGASAKI_YELLOW "TWB64 020 - Nijigasaki Yellow"
OPTION_VAL_TWB64_021_GAMATE_VER "TWB64 021 - Gamate Ver."
OPTION_VAL_TWB64_022_GREENSCALE_VER "TWB64 022 - Greenscale Ver."
OPTION_VAL_TWB64_023_ODYSSEY_GOLD "TWB64 023 - Odyssey Gold"
OPTION_VAL_TWB64_024_SUPER_SAIYAN_GOD "TWB64 024 - Super Saiyan God"
OPTION_VAL_TWB64_025_SUPER_SAIYAN_BLUE "TWB64 025 - Super Saiyan Blue"
OPTION_VAL_TWB64_026_BIZARRE_PINK "TWB64 026 - Bizarre Pink"
OPTION_VAL_TWB64_027_NINTENDO_SWITCH_LITE_VER "TWB64 027 - Nintendo Switch Lite Ver."
OPTION_VAL_TWB64_028_GAME_COM_VER "TWB64 028 - Game.com Ver."
OPTION_VAL_TWB64_029_SANRIO_PINK "TWB64 029 - Sanrio Pink"
OPTION_VAL_TWB64_030_BANDAI_NAMCO_VER "TWB64 030 - BANDAI NAMCO Ver."
OPTION_VAL_TWB64_031_COSMO_GREEN "TWB64 031 - Cosmo Green"
OPTION_VAL_TWB64_032_WANDA_PINK "TWB64 032 - Wanda Pink"
OPTION_VAL_TWB64_033_LINK_S_AWAKENING_DX_VER "TWB64 033 - Link's Awakening DX Ver."
OPTION_VAL_TWB64_034_TRAVEL_WOOD "TWB64 034 - Travel Wood"
OPTION_VAL_TWB64_035_POKEMON_VER "TWB64 035 - Pokemon Ver."
OPTION_VAL_TWB64_036_GAME_GRUMP_ORANGE "TWB64 036 - Game Grump Orange"
OPTION_VAL_TWB64_037_SCOOBY_DOO_MYSTERY_VER "TWB64 037 - Scooby-Doo Mystery Ver."
OPTION_VAL_TWB64_038_POKEMON_MINI_VER "TWB64 038 - Pokemon mini Ver."
OPTION_VAL_TWB64_039_SUPERVISION_VER "TWB64 039 - Supervision Ver."
OPTION_VAL_TWB64_040_DMG_VER "TWB64 040 - DMG Ver."
OPTION_VAL_TWB64_041_POCKET_VER "TWB64 041 - Pocket Ver."
OPTION_VAL_TWB64_042_LIGHT_VER "TWB64 042 - Light Ver."
OPTION_VAL_TWB64_043_MIRAITOWA_BLUE "TWB64 043 - Miraitowa Blue"
OPTION_VAL_TWB64_044_SOMEITY_PINK "TWB64 044 - Someity Pink"
OPTION_VAL_TWB64_045_PIKACHU_YELLOW "TWB64 045 - Pikachu Yellow"
OPTION_VAL_TWB64_046_EEVEE_BROWN "TWB64 046 - Eevee Brown"
OPTION_VAL_TWB64_047_MICROVISION_VER "TWB64 047 - Microvision Ver."
OPTION_VAL_TWB64_048_TI_83_VER "TWB64 048 - TI-83 Ver."
OPTION_VAL_TWB64_049_AEGIS_CHERRY "TWB64 049 - Aegis Cherry"
OPTION_VAL_TWB64_050_LABO_FAWN "TWB64 050 - Labo Fawn"
OPTION_VAL_TWB64_051_MILLION_LIVE_GOLD "TWB64 051 - MILLION LIVE GOLD!"
OPTION_VAL_TWB64_052_TOKYO_MIDTOWN_VER "TWB64 052 - Tokyo Midtown Ver."
OPTION_VAL_TWB64_053_VMU_VER "TWB64 053 - VMU Ver."
OPTION_VAL_TWB64_054_GAME_MASTER_VER "TWB64 054 - Game Master Ver."
OPTION_VAL_TWB64_055_ANDROID_GREEN "TWB64 055 - Android Green"
OPTION_VAL_TWB64_056_TICKETMASTER_AZURE "TWB64 056 - Ticketmaster Azure"
OPTION_VAL_TWB64_057_GOOGLE_RED "TWB64 057 - Google Red"
OPTION_VAL_TWB64_058_GOOGLE_BLUE "TWB64 058 - Google Blue"
OPTION_VAL_TWB64_059_GOOGLE_YELLOW "TWB64 059 - Google Yellow"
OPTION_VAL_TWB64_060_GOOGLE_GREEN "TWB64 060 - Google Green"
OPTION_VAL_TWB64_061_WONDERSWAN_VER "TWB64 061 - WonderSwan Ver."
OPTION_VAL_TWB64_062_NEO_GEO_POCKET_VER "TWB64 062 - Neo Geo Pocket Ver."
OPTION_VAL_TWB64_063_DEW_GREEN "TWB64 063 - Dew Green"
OPTION_VAL_TWB64_064_COCA_COLA_RED "TWB64 064 - Coca-Cola Red"
OPTION_VAL_TWB64_065_GAMEKING_VER "TWB64 065 - GameKing Ver."
OPTION_VAL_TWB64_066_DO_THE_DEW_VER "TWB64 066 - Do The Dew Ver."
OPTION_VAL_TWB64_067_DIGIVICE_VER "TWB64 067 - Digivice Ver."
OPTION_VAL_TWB64_068_BIKINI_BOTTOM_VER "TWB64 068 - Bikini Bottom Ver."
OPTION_VAL_TWB64_069_BLOSSOM_PINK "TWB64 069 - Blossom Pink"
OPTION_VAL_TWB64_070_BUBBLES_BLUE "TWB64 070 - Bubbles Blue"
OPTION_VAL_TWB64_071_BUTTERCUP_GREEN "TWB64 071 - Buttercup Green"
OPTION_VAL_TWB64_072_NASCAR_VER "TWB64 072 - NASCAR Ver."
OPTION_VAL_TWB64_073_LEMON_LIME_GREEN "TWB64 073 - Lemon-Lime Green"
OPTION_VAL_TWB64_074_MEGA_MAN_V_VER "TWB64 074 - Mega Man V Ver."
OPTION_VAL_TWB64_075_TAMAGOTCHI_VER "TWB64 075 - Tamagotchi Ver."
OPTION_VAL_TWB64_076_PHANTOM_RED "TWB64 076 - Phantom Red"
OPTION_VAL_TWB64_077_HALLOWEEN_VER "TWB64 077 - Halloween Ver."
OPTION_VAL_TWB64_078_CHRISTMAS_VER "TWB64 078 - Christmas Ver."
OPTION_VAL_TWB64_079_CARDCAPTOR_PINK "TWB64 079 - Cardcaptor Pink"
OPTION_VAL_TWB64_080_PRETTY_GUARDIAN_GOLD "TWB64 080 - Pretty Guardian Gold"
OPTION_VAL_TWB64_081_CAMOFLAUGE_VER "TWB64 081 - Camoflauge Ver."
OPTION_VAL_TWB64_082_LEGENDARY_SUPER_SAIYAN "TWB64 082 - Legendary Super Saiyan"
OPTION_VAL_TWB64_083_SUPER_SAIYAN_ROSE "TWB64 083 - Super Saiyan Rose"
OPTION_VAL_TWB64_084_SUPER_SAIYAN "TWB64 084 - Super Saiyan"
OPTION_VAL_TWB64_085_MASTERED_ULTRA_INSTINCT "TWB64 085 - Mastered Ultra Instinct"
OPTION_VAL_TWB64_086_SAINT_SNOW_RED "TWB64 086 - Saint Snow Red"
OPTION_VAL_TWB64_087_YELLOW_BANANA "TWB64 087 - Yellow Banana"
OPTION_VAL_TWB64_088_GREEN_BANANA "TWB64 088 - Green Banana"
OPTION_VAL_TWB64_089_SUPER_SAIYAN_3 "TWB64 089 - Super Saiyan 3"
OPTION_VAL_TWB64_090_SUPER_SAIYAN_BLUE_EVOLVED "TWB64 090 - Super Saiyan Blue Evolved"
OPTION_VAL_TWB64_091_POCKET_TALES_VER "TWB64 091 - Pocket Tales Ver."
OPTION_VAL_TWB64_092_INVESTIGATION_YELLOW "TWB64 092 - Investigation Yellow"
OPTION_VAL_TWB64_093_S_E_E_S_BLUE "TWB64 093 - S.E.E.S. Blue"
OPTION_VAL_TWB64_094_GAME_AWARDS_CYAN "TWB64 094 - Game Awards Cyan"
OPTION_VAL_TWB64_095_HOKAGE_ORANGE "TWB64 095 - Hokage Orange"
OPTION_VAL_TWB64_096_STRAW_HAT_RED "TWB64 096 - Straw Hat Red"
OPTION_VAL_TWB64_097_SWORD_ART_CYAN "TWB64 097 - Sword Art Cyan"
OPTION_VAL_TWB64_098_DEKU_ALPHA_EMERALD "TWB64 098 - Deku Alpha Emerald"
OPTION_VAL_TWB64_099_BLUE_STRIPES_VER "TWB64 099 - Blue Stripes Ver."
OPTION_VAL_TWB64_100_STONE_ORANGE "TWB64 100 - Stone Orange"
GAMBATTE_GB_PALETTE_TWB64_2_LABEL "> TWB64 - Pack 2 Palette"
GAMBATTE_GB_PALETTE_TWB64_2_INFO_0 "Selects internal colorization palette when 'Internal Palette' is set to 'TWB64 - Pack 2'."
OPTION_VAL_TWB64_101_765PRO_PINK "TWB64 101 - 765PRO Pink"
OPTION_VAL_TWB64_102_CINDERELLA_BLUE "TWB64 102 - CINDERELLA Blue"
OPTION_VAL_TWB64_103_MILLION_YELLOW "TWB64 103 - MILLION Yellow!"
OPTION_VAL_TWB64_104_SIDEM_GREEN "TWB64 104 - SideM Green"
OPTION_VAL_TWB64_105_SHINY_SKY_BLUE "TWB64 105 - SHINY Sky Blue"
OPTION_VAL_TWB64_106_ANGRY_VOLCANO_VER "TWB64 106 - Angry Volcano Ver."
OPTION_VAL_TWB64_107_YO_KAI_PINK "TWB64 107 - Yo-kai Pink"
OPTION_VAL_TWB64_108_YO_KAI_GREEN "TWB64 108 - Yo-kai Green"
OPTION_VAL_TWB64_109_YO_KAI_BLUE "TWB64 109 - Yo-kai Blue"
OPTION_VAL_TWB64_110_YO_KAI_PURPLE "TWB64 110 - Yo-kai Purple"
OPTION_VAL_TWB64_111_AQUATIC_IRO "TWB64 111 - Aquatic Iro"
OPTION_VAL_TWB64_112_TEA_MIDORI "TWB64 112 - Tea Midori"
OPTION_VAL_TWB64_113_SAKURA_PINK "TWB64 113 - Sakura Pink"
OPTION_VAL_TWB64_114_WISTERIA_MURASAKI "TWB64 114 - Wisteria Murasaki"
OPTION_VAL_TWB64_115_ONI_AKA "TWB64 115 - Oni Aka"
OPTION_VAL_TWB64_116_GOLDEN_KIIRO "TWB64 116 - Golden Kiiro"
OPTION_VAL_TWB64_117_SILVER_SHIRO "TWB64 117 - Silver Shiro"
OPTION_VAL_TWB64_118_FRUITY_ORANGE "TWB64 118 - Fruity Orange"
OPTION_VAL_TWB64_119_AKB48_PINK "TWB64 119 - AKB48 Pink"
OPTION_VAL_TWB64_120_MIKU_BLUE "TWB64 120 - Miku Blue"
OPTION_VAL_TWB64_121_FAIRY_TAIL_RED "TWB64 121 - Fairy Tail Red"
OPTION_VAL_TWB64_122_SURVEY_CORPS_BROWN "TWB64 122 - Survey Corps Brown"
OPTION_VAL_TWB64_123_ISLAND_GREEN "TWB64 123 - Island Green"
OPTION_VAL_TWB64_124_MANIA_PLUS_GREEN "TWB64 124 - Mania Plus Green"
OPTION_VAL_TWB64_125_NINJA_TURTLE_GREEN "TWB64 125 - Ninja Turtle Green"
OPTION_VAL_TWB64_126_SLIME_BLUE "TWB64 126 - Slime Blue"
OPTION_VAL_TWB64_127_LIME_MIDORI "TWB64 127 - Lime Midori"
OPTION_VAL_TWB64_128_GHOSTLY_AOI "TWB64 128 - Ghostly Aoi"
OPTION_VAL_TWB64_129_RETRO_BOGEDA "TWB64 129 - Retro Bogeda"
OPTION_VAL_TWB64_130_ROYAL_BLUE "TWB64 130 - Royal Blue"
OPTION_VAL_TWB64_131_NEON_PURPLE "TWB64 131 - Neon Purple"
OPTION_VAL_TWB64_132_NEON_ORANGE "TWB64 132 - Neon Orange"
OPTION_VAL_TWB64_133_MOONLIGHT_VISION "TWB64 133 - Moonlight Vision"
OPTION_VAL_TWB64_134_TOKYO_RED "TWB64 134 - Tokyo Red"
OPTION_VAL_TWB64_135_PARIS_GOLD "TWB64 135 - Paris Gold"
OPTION_VAL_TWB64_136_BEIJING_BLUE "TWB64 136 - Beijing Blue"
OPTION_VAL_TWB64_137_PAC_MAN_YELLOW "TWB64 137 - Pac-Man Yellow"
OPTION_VAL_TWB64_138_IRISH_GREEN "TWB64 138 - Irish Green"
OPTION_VAL_TWB64_139_KAKAROT_ORANGE "TWB64 139 - Kakarot Orange"
OPTION_VAL_TWB64_140_DRAGON_BALL_ORANGE "TWB64 140 - Dragon Ball Orange"
OPTION_VAL_TWB64_141_CHRISTMAS_GOLD "TWB64 141 - Christmas Gold"
OPTION_VAL_TWB64_142_PEPSI_BLUE "TWB64 142 - Pepsi Blue"
OPTION_VAL_TWB64_143_BUBBLUN_GREEN "TWB64 143 - Bubblun Green"
OPTION_VAL_TWB64_144_BOBBLUN_BLUE "TWB64 144 - Bobblun Blue"
OPTION_VAL_TWB64_145_BAJA_BLAST_STORM "TWB64 145 - Baja Blast Storm"
OPTION_VAL_TWB64_146_OLYMPIC_GOLD "TWB64 146 - Olympic Gold"
OPTION_VAL_TWB64_147_VALUE_ORANGE "TWB64 147 - Value Orange"
OPTION_VAL_TWB64_148_LIELLA_PURPLE "TWB64 148 - Liella Purple!"
OPTION_VAL_TWB64_149_OLYMPIC_SILVER "TWB64 149 - Olympic Silver"
OPTION_VAL_TWB64_150_OLYMPIC_BRONZE "TWB64 150 - Olympic Bronze"
OPTION_VAL_TWB64_151_ANA_SKY_BLUE "TWB64 151 - ANA Sky Blue"
OPTION_VAL_TWB64_152_NIJIGASAKI_ORANGE "TWB64 152 - Nijigasaki Orange"
OPTION_VAL_TWB64_153_HOLOBLUE "TWB64 153 - HoloBlue"
OPTION_VAL_TWB64_154_WRESTLING_RED "TWB64 154 - Wrestling Red"
OPTION_VAL_TWB64_155_YOSHI_EGG_GREEN "TWB64 155 - Yoshi Egg Green"
OPTION_VAL_TWB64_156_POKEDEX_RED "TWB64 156 - Pokedex Red"
OPTION_VAL_TWB64_157_DISNEY_DREAM_BLUE "TWB64 157 - Disney Dream Blue"
OPTION_VAL_TWB64_158_XBOX_GREEN "TWB64 158 - Xbox Green"
OPTION_VAL_TWB64_159_SONIC_MEGA_BLUE "TWB64 159 - Sonic Mega Blue"
OPTION_VAL_TWB64_160_G4_ORANGE "TWB64 160 - G4 Orange"
OPTION_VAL_TWB64_161_SCARLETT_GREEN "TWB64 161 - Scarlett Green"
OPTION_VAL_TWB64_162_GLITCHY_BLUE "TWB64 162 - Glitchy Blue"
OPTION_VAL_TWB64_163_CLASSIC_LCD "TWB64 163 - Classic LCD"
OPTION_VAL_TWB64_164_3DS_VIRTUAL_CONSOLE_VER "TWB64 164 - 3DS Virtual Console Ver."
OPTION_VAL_TWB64_165_POCKETSTATION_VER "TWB64 165 - PocketStation Ver."
OPTION_VAL_TWB64_166_GAME_AND_GOLD "TWB64 166 - Game and Gold"
OPTION_VAL_TWB64_167_SMURFY_BLUE "TWB64 167 - Smurfy Blue"
OPTION_VAL_TWB64_168_SWAMPY_OGRE_GREEN "TWB64 168 - Swampy Ogre Green"
OPTION_VAL_TWB64_169_SAILOR_SPINACH_GREEN "TWB64 169 - Sailor Spinach Green"
OPTION_VAL_TWB64_170_SHENRON_GREEN "TWB64 170 - Shenron Green"
OPTION_VAL_TWB64_171_BERSERK_BLOOD "TWB64 171 - Berserk Blood"
OPTION_VAL_TWB64_172_SUPER_STAR_PINK "TWB64 172 - Super Star Pink"
OPTION_VAL_TWB64_173_GAMEBUINO_CLASSIC_VER "TWB64 173 - Gamebuino Classic Ver."
OPTION_VAL_TWB64_174_BARBIE_PINK "TWB64 174 - Barbie Pink"
OPTION_VAL_TWB64_175_STAR_COMMAND_GREEN "TWB64 175 - Star Command Green"
OPTION_VAL_TWB64_176_NOKIA_3310_VER "TWB64 176 - Nokia 3310 Ver."
OPTION_VAL_TWB64_177_CLOVER_GREEN "TWB64 177 - Clover Green"
OPTION_VAL_TWB64_178_CRASH_ORANGE "TWB64 178 - Crash Orange"
OPTION_VAL_TWB64_179_FAMICOM_DISK_YELLOW "TWB64 179 - Famicom Disk Yellow"
OPTION_VAL_TWB64_180_TEAM_ROCKET_RED "TWB64 180 - Team Rocket Red"
OPTION_VAL_TWB64_181_SEIKO_TIMER_YELLOW "TWB64 181 - SEIKO Timer Yellow"
OPTION_VAL_TWB64_182_PINK109 "TWB64 182 - PINK109"
OPTION_VAL_TWB64_183_DORAEMON_BLUE "TWB64 183 - Doraemon Blue"
OPTION_VAL_TWB64_184_FURY_BLUE "TWB64 184 - Fury Blue"
OPTION_VAL_TWB64_185_ROCKSTAR_ORANGE "TWB64 185 - Rockstar Orange"
OPTION_VAL_TWB64_186_PUYO_PUYO_GREEN "TWB64 186 - Puyo Puyo Green"
OPTION_VAL_TWB64_187_SUSAN_G_PINK "TWB64 187 - Susan G. Pink"
OPTION_VAL_TWB64_188_PIZZA_HUT_RED "TWB64 188 - Pizza Hut Red"
OPTION_VAL_TWB64_189_PLUMBOB_GREEN "TWB64 189 - Plumbob Green"
OPTION_VAL_TWB64_190_GRAND_IVORY "TWB64 190 - Grand Ivory"
OPTION_VAL_TWB64_191_DEMON_S_GOLD "TWB64 191 - Demon's Gold"
OPTION_VAL_TWB64_192_SEGA_TOKYO_BLUE "TWB64 192 - SEGA Tokyo Blue"
OPTION_VAL_TWB64_193_CHAMPION_BLUE "TWB64 193 - Champion Blue"
OPTION_VAL_TWB64_194_DK_BARREL_BROWN "TWB64 194 - DK Barrel Brown"
OPTION_VAL_TWB64_195_EVANGELION_GREEN "TWB64 195 - Evangelion Green"
OPTION_VAL_TWB64_196_EQUESTRIAN_PURPLE "TWB64 196 - Equestrian Purple"
OPTION_VAL_TWB64_197_AUTOBOT_RED "TWB64 197 - Autobot Red"
OPTION_VAL_TWB64_198_NICONICO_SEA_GREEN "TWB64 198 - Niconico Sea Green"
OPTION_VAL_TWB64_199_DURACELL_COPPER "TWB64 199 - Duracell Copper"
OPTION_VAL_TWB64_200_TOKYO_SKYTREE_CLOUDY_BLUE "TWB64 200 - TOKYO SKYTREE CLOUDY BLUE"
GAMBATTE_GBC_COLOR_CORRECTION_LABEL "Color Correction"
GAMBATTE_GBC_COLOR_CORRECTION_INFO_0 "Adjusts output colors to match the display of real Game Boy Color hardware. 'GBC Only' ensures that correction will only be applied when playing Game Boy Color games, or when using a Game Boy Color palette to colorize a Game Boy game. 'Always' applies color correction to all content, and will produce unexpected/suboptimal results when using 'GB' or 'SGB' internal color palettes."
OPTION_VAL_GBC_ONLY "GBC Only"
OPTION_VAL_ALWAYS "Always"
GAMBATTE_GBC_COLOR_CORRECTION_MODE_LABEL "Color Correction Mode"
GAMBATTE_GBC_COLOR_CORRECTION_MODE_INFO_0 "Specifies method used when performing color correction. 'Accurate' produces output almost indistinguishable from a real Game Boy Color LCD panel. 'Fast' merely darkens colors and reduces saturation, and may be used on low-end hardware if the 'Accurate' method is too slow."
OPTION_VAL_ACCURATE "Accurate"
OPTION_VAL_FAST "Fast"
GAMBATTE_GBC_FRONTLIGHT_POSITION_LABEL "Color Correction - Frontlight Position"
GAMBATTE_GBC_FRONTLIGHT_POSITION_INFO_0 "Simulates the physical response of the Game Boy Color LCD panel when illuminated from different angles. 'Central' represents standard color reproduction. 'Above Screen' increases brightness. 'Below Screen' reduces brightness. This setting only applies when 'Color Correction Mode' is set to 'Accurate'."
OPTION_VAL_CENTRAL "Central"
OPTION_VAL_ABOVE_SCREEN "Above Screen"
OPTION_VAL_BELOW_SCREEN "Below Screen"
GAMBATTE_DARK_FILTER_LEVEL_LABEL "Dark Filter Level (percent)"
GAMBATTE_DARK_FILTER_LEVEL_INFO_0 "Enable luminosity-based brightness reduction. May be used to avoid glare/eye strain when playing games with white backgrounds, which are intended for display on a non-backlit Game Boy Color and can therefore appear uncomfortably bright when viewed on a modern backlit screen."
GAMBATTE_GB_HWMODE_LABEL "Emulated Hardware (restart)"
GAMBATTE_GB_HWMODE_INFO_0 "Specify which type of hardware to emulate. 'Auto' is recommended. Selecting 'GBA' unlocks extra features in certain 'GBA enhanced' Game Boy Color games (Shantae, Wendy - Every Witch Way, Legend of Zelda: Oracle of Seasons/Ages...)."
OPTION_VAL_GB "GB"
OPTION_VAL_GBA "GBA"
GAMBATTE_GB_BOOTLOADER_LABEL "Use Official Bootloader (restart)"
GAMBATTE_GB_BOOTLOADER_INFO_0 "Enable support for official Game Boy and Game Boy Color bootloaders, with corresponding start-up logo animations."
GAMBATTE_MIX_FRAMES_LABEL "Interframe Blending"
GAMBATTE_MIX_FRAMES_INFO_0 "Simulates LCD ghosting effects. 'Simple' performs a 50:50 mix of the current and previous frames. 'LCD Ghosting' mimics natural LCD response times by combining multiple buffered frames. 'Simple' blending is required when playing games that rely on LCD ghosting for transparency effects (Wave Race, Ballistic, Chikyuu Kaihou Gun ZAS...)."
OPTION_VAL_MIX "Simple"
OPTION_VAL_LCD_GHOSTING "LCD Ghosting (Accurate)"
OPTION_VAL_LCD_GHOSTING_FAST "LCD Ghosting (Fast)"
GAMBATTE_UP_DOWN_ALLOWED_LABEL "Allow Opposing Directions"
GAMBATTE_UP_DOWN_ALLOWED_INFO_0 "Enabling this will allow pressing / quickly alternating / holding both left and right (or up and down) directions at the same time. This may cause movement-based glitches."
GAMBATTE_TURBO_PERIOD_LABEL "Turbo Button Period"
GAMBATTE_TURBO_PERIOD_INFO_0 "Specify the repeat interval (in frames) when holding down the Turbo A/B buttons."
GAMBATTE_RUMBLE_LEVEL_LABEL "Gamepad Rumble Strength"
GAMBATTE_RUMBLE_LEVEL_INFO_0 "Enables haptic feedback effects for supported games (Pokemon Pinball, Perfect Dark...)."
GAMBATTE_SHOW_GB_LINK_SETTINGS_LABEL "Show Game Boy Link Settings"
GAMBATTE_SHOW_GB_LINK_SETTINGS_INFO_0 "Enable configuration of networked 'Game Boy Link' (multiplayer) options. NOTE: Quick Menu may need to be toggled for this setting to take effect."
GAMBATTE_GB_LINK_MODE_LABEL "Game Boy Link Mode"
GAMBATTE_GB_LINK_MODE_LABEL_CAT "Link Mode"
GAMBATTE_GB_LINK_MODE_INFO_0 "When enabling networked 'Game Boy Link' functionality, specify whether current instance should run as a server or client."
OPTION_VAL_NOT_CONNECTED "Not Connected"
OPTION_VAL_NETWORK_SERVER "Network Server"
OPTION_VAL_NETWORK_CLIENT "Network Client"
GAMBATTE_GB_LINK_NETWORK_PORT_LABEL "Network Link Port"
GAMBATTE_GB_LINK_NETWORK_PORT_LABEL_CAT "Port"
GAMBATTE_GB_LINK_NETWORK_PORT_INFO_0 "Specify port used for 'Game Boy Link' network communication."
GAMBATTE_GB_LINK_NETWORK_SERVER_IP_1_LABEL "Network Link Server Address Pt. 01: x__.___.___.___"
GAMBATTE_GB_LINK_NETWORK_SERVER_IP_1_LABEL_CAT "Server Address Pt. 01: x__.___.___.___"
GAMBATTE_GB_LINK_NETWORK_SERVER_IP_1_INFO_0 "1st digit of remote 'Game Boy Link' network server IP address. Only used when 'Game Boy Link Mode' is set to 'Network Client'."
GAMBATTE_GB_LINK_NETWORK_SERVER_IP_1_INFO_1 "1st digit of remote 'Game Boy Link' network server IP address. Only used when 'Link Mode' is set to 'Network Client'."
GAMBATTE_GB_LINK_NETWORK_SERVER_IP_2_LABEL "Network Link Server Address Pt. 02: _x_.___.___.___"
GAMBATTE_GB_LINK_NETWORK_SERVER_IP_2_LABEL_CAT "Server Address Pt. 02: _x_.___.___.___"
GAMBATTE_GB_LINK_NETWORK_SERVER_IP_2_INFO_0 "2nd digit of remote 'Game Boy Link' network server IP address. Only used when 'Game Boy Link Mode' is set to 'Network Client'."
GAMBATTE_GB_LINK_NETWORK_SERVER_IP_2_INFO_1 "2nd digit of remote 'Game Boy Link' network server IP address. Only used when 'Link Mode' is set to 'Network Client'."
GAMBATTE_GB_LINK_NETWORK_SERVER_IP_3_LABEL "Network Link Server Address Pt. 03: __x.___.___.___"
GAMBATTE_GB_LINK_NETWORK_SERVER_IP_3_LABEL_CAT "Server Address Pt. 03: __x.___.___.___"
GAMBATTE_GB_LINK_NETWORK_SERVER_IP_3_INFO_0 "3rd digit of remote 'Game Boy Link' network server IP address. Only used when 'Game Boy Link Mode' is set to 'Network Client'."
GAMBATTE_GB_LINK_NETWORK_SERVER_IP_3_INFO_1 "3rd digit of remote 'Game Boy Link' network server IP address. Only used when 'Link Mode' is set to 'Network Client'."
GAMBATTE_GB_LINK_NETWORK_SERVER_IP_4_LABEL "Network Link Server Address Pt. 04: ___.x__.___.___"
GAMBATTE_GB_LINK_NETWORK_SERVER_IP_4_LABEL_CAT "Server Address Pt. 04: ___.x__.___.___"
GAMBATTE_GB_LINK_NETWORK_SERVER_IP_4_INFO_0 "4th digit of remote 'Game Boy Link' network server IP address. Only used when 'Game Boy Link Mode' is set to 'Network Client'."
GAMBATTE_GB_LINK_NETWORK_SERVER_IP_4_INFO_1 "4th digit of remote 'Game Boy Link' network server IP address. Only used when 'Link Mode' is set to 'Network Client'."
GAMBATTE_GB_LINK_NETWORK_SERVER_IP_5_LABEL "Network Link Server Address Pt. 05: ___._x_.___.___"
GAMBATTE_GB_LINK_NETWORK_SERVER_IP_5_LABEL_CAT "Server Address Pt. 05: ___._x_.___.___"
GAMBATTE_GB_LINK_NETWORK_SERVER_IP_5_INFO_0 "5th digit of remote 'Game Boy Link' network server IP address. Only used when 'Game Boy Link Mode' is set to 'Network Client'."
GAMBATTE_GB_LINK_NETWORK_SERVER_IP_5_INFO_1 "5th digit of remote 'Game Boy Link' network server IP address. Only used when 'Link Mode' is set to 'Network Client'."
GAMBATTE_GB_LINK_NETWORK_SERVER_IP_6_LABEL "Network Link Server Address Pt. 06: ___.__x.___.___"
GAMBATTE_GB_LINK_NETWORK_SERVER_IP_6_LABEL_CAT "Server Address Pt. 06: ___.__x.___.___"
GAMBATTE_GB_LINK_NETWORK_SERVER_IP_6_INFO_0 "6th digit of remote 'Game Boy Link' network server IP address. Only used when 'Game Boy Link Mode' is set to 'Network Client'."
GAMBATTE_GB_LINK_NETWORK_SERVER_IP_6_INFO_1 "6th digit of remote 'Game Boy Link' network server IP address. Only used when 'Link Mode' is set to 'Network Client'."
GAMBATTE_GB_LINK_NETWORK_SERVER_IP_7_LABEL "Network Link Server Address Pt. 07: ___.___.x__.___"
GAMBATTE_GB_LINK_NETWORK_SERVER_IP_7_LABEL_CAT "Server Address Pt. 07: ___.___.x__.___"
GAMBATTE_GB_LINK_NETWORK_SERVER_IP_7_INFO_0 "7th digit of remote 'Game Boy Link' network server IP address. Only used when 'Game Boy Link Mode' is set to 'Network Client'."
GAMBATTE_GB_LINK_NETWORK_SERVER_IP_7_INFO_1 "7th digit of remote 'Game Boy Link' network server IP address. Only used when 'Link Mode' is set to 'Network Client'."
GAMBATTE_GB_LINK_NETWORK_SERVER_IP_8_LABEL "Network Link Server Address Pt. 08: ___.___._x_.___"
GAMBATTE_GB_LINK_NETWORK_SERVER_IP_8_LABEL_CAT "Server Address Pt. 08: ___.___._x_.___"
GAMBATTE_GB_LINK_NETWORK_SERVER_IP_8_INFO_0 "8th digit of remote 'Game Boy Link' network server IP address. Only used when 'Game Boy Link Mode' is set to 'Network Client'."
GAMBATTE_GB_LINK_NETWORK_SERVER_IP_8_INFO_1 "8th digit of remote 'Game Boy Link' network server IP address. Only used when 'Link Mode' is set to 'Network Client'."
GAMBATTE_GB_LINK_NETWORK_SERVER_IP_9_LABEL "Network Link Server Address Pt. 09: ___.___.__x.___"
GAMBATTE_GB_LINK_NETWORK_SERVER_IP_9_LABEL_CAT "Server Address Pt. 09: ___.___.__x.___"
GAMBATTE_GB_LINK_NETWORK_SERVER_IP_9_INFO_0 "9th digit of remote 'Game Boy Link' network server IP address. Only used when 'Game Boy Link Mode' is set to 'Network Client'."
GAMBATTE_GB_LINK_NETWORK_SERVER_IP_9_INFO_1 "9th digit of remote 'Game Boy Link' network server IP address. Only used when 'Link Mode' is set to 'Network Client'."
GAMBATTE_GB_LINK_NETWORK_SERVER_IP_10_LABEL "Network Link Server Address Pt. 10: ___.___.___.x__"
GAMBATTE_GB_LINK_NETWORK_SERVER_IP_10_LABEL_CAT "Server Address Pt. 10: ___.___.___.x__"
GAMBATTE_GB_LINK_NETWORK_SERVER_IP_10_INFO_0 "10th digit of remote 'Game Boy Link' network server IP address. Only used when 'Game Boy Link Mode' is set to 'Network Client'."
GAMBATTE_GB_LINK_NETWORK_SERVER_IP_10_INFO_1 "10th digit of remote 'Game Boy Link' network server IP address. Only used when 'Link Mode' is set to 'Network Client'."
GAMBATTE_GB_LINK_NETWORK_SERVER_IP_11_LABEL "Network Link Server Address Pt. 11: ___.___.___._x_"
GAMBATTE_GB_LINK_NETWORK_SERVER_IP_11_LABEL_CAT "Server Address Pt. 11: ___.___.___._x_"
GAMBATTE_GB_LINK_NETWORK_SERVER_IP_11_INFO_0 "11th digit of remote 'Game Boy Link' network server IP address. Only used when 'Game Boy Link Mode' is set to 'Network Client'."
GAMBATTE_GB_LINK_NETWORK_SERVER_IP_11_INFO_1 "11th digit of remote 'Game Boy Link' network server IP address. Only used when 'Link Mode' is set to 'Network Client'."
GAMBATTE_GB_LINK_NETWORK_SERVER_IP_12_LABEL "Network Link Server Address Pt. 12: ___.___.___.__x"
GAMBATTE_GB_LINK_NETWORK_SERVER_IP_12_LABEL_CAT "Server Address Pt. 12: ___.___.___.__x"
GAMBATTE_GB_LINK_NETWORK_SERVER_IP_12_INFO_0 "12th digit of remote 'Game Boy Link' network server IP address. Only used when 'Game Boy Link Mode' is set to 'Network Client'."
GAMBATTE_GB_LINK_NETWORK_SERVER_IP_12_INFO_1 "12th digit of remote 'Game Boy Link' network server IP address. Only used when 'Link Mode' is set to 'Network Client'."
